### ISSUE TITLE
Datasets provided in DICOM and NIFTI formats does not match

### ISSUE THREAD

**Issue by neerajaj96** [theibsi/data_sets#2]
I can see that the datasets provided in Dicom and NIFTI formats in https://github.com/theibsi/data_sets/tree/master/ibsi_1_digital_phantom have different voxels and Voxel spacing. And hence I would like to know if both these datasets are expected to return the same feature values that match with the IBSI results. 
Could you please help me to confirm this?

**Comment by alexzwanenburg** [comment]
Confirmed. I will deprecate the DICOM files for digital phantom until we can correct the issue.
